### PR TITLE
Added ICAN addresses

### PR DESCRIPTION
**Pull request by rastislavcore**
ICAN addresses - popular in Core networks

### CODE REVIEW

**Review by sergical — COMMENTED** [review]
<3 Thank you! Wanna update the CHANGELOG and update `package.json` to `1.0.1` and then the merge should automatically publish a new version?

**Comment by rastislavcore** [comment]
Let me know if you need any rebase of this PR. Anyway tests are passing. But CI/CD should be improved. The optional flag to force checksum is missing also - which may be necessary in some cases. Anyway I can help you with the next PR after this is merged.

**Comment by sergical** [comment]
I believe the publish step in the CI will fail once this is in `main` because the version is going to be the same. 

I am all ears on how to improve the CI/CD and appreciate the patience

Also if you could run the format command, do you think it should run on pre-commit with husky?

**Comment by rastislavcore** [comment]
I appreciate your work, because on whole internet there is lack of typescript wallet verificators, especially lightweight version.

I did some ironing and check are passing.

I will send you next PR with my version CI/CD, feel free to modify it or take from it what you need. Pre-commit is not good idea IMHO, it will give more issues later on. I am levriging on GH actions mostly. All the online CI services are OK, but it should be picked wisely. Most of them are not needed anymore.

Then, I will show what you mean in next PR. #4

**Review by sergical — APPROVED** [review]

**Pull request merged**
