### PR TITLE
CI/CD improvements

### PR DESCRIPTION
**Pull request by rastislavcore**
CI/CD proposals:

Why is it good to have provenance?

> Supply Chain Security; Verification Benefits; Visual Indicators

Why I hate Dependabot and locks?

> Dependabot become contributor; Not 100% working for agile code; Mess in PR requests

Why I am putting publish on release?

> Good workflow for automtion, probably you don't want release version by commit to main or specific tag. This proves to me as good practice.

I hate empty spaces also :)

### CODE REVIEW

**Comment by sergical** [comment]
Whats the reason for adding lockfiles to `.gitignore`? CI fails without it: https://github.com/sergical/blockchain-wallet-validator/actions/runs/12453451331/job/34769613322?pr=4

**Comment by rastislavcore** [comment]
There is many reasons, which can be pro for avoiding putting it inside.
But in other hand a lot of people like it to keep. Then we have dilema 50:50

We have points and counterpoints. I am the "advocate" of minimalization and clean solutions.

Point: it causes unnecessary conflicts during merges
Counter: conflicts are typically easy to resolve

Point: it’s redundant
Counter: lock complements package.json

Basically there are two scenarios:

- keep locks

or

- fix CI/CD to work without them

Because you are developing the library I excluded it - for libraries, the primary concern is compatibility with a wide range of dependencies, not locking specific versions.

And because your library is stated as lightweight, I decided to exclude - Focus on Development Velocity.

I can fix for you CI/CD. But final decision is on you. What you like to do? @sergical

**Comment by sergical** [comment]
@rastislavcore i agree, this is a lightweight package with very few dependencies so removing dependabot and optimizing for the ci/cd to work without lockfiles sounds good to me 🙏

**Comment by rastislavcore** [comment]
I will fix CI then...

**Review by sergical — APPROVED** [review]
Thank you!

**Comment by rastislavcore** [comment]
Good job. My compliments to your work 🤝

**Pull request merged**
